### ISSUE TITLE
README.md references a `/data` folder - what is it?

### ISSUE THREAD

**Issue by micklynch** [jgwehr/homelab-docker#101]
## Description
The README references a `/data` folder. 
https://github.com/jgwehr/homelab-docker/blob/bf4da8767e0639bf835583f24848a67e77faee3b/README.md?plain=1#L120

However, in the folder structure, this location does not exist. Is this something that needs to be created or is this supposed to reference `/mnt/storage` folder instead?

**Comment by micklynch** [comment]
And follow-up question, do I need to run everything as root?

**Comment by jgwehr** [comment]
Hi @micklynch - thanks for reaching out!

> Is this something that needs to be created or is this supposed to reference /mnt/storage folder instead?

You found a mistake in the readme - I'll fix this as soon as I can. Until I can get this updated, the wiki may be a better reference: https://github.com/jgwehr/homelab-docker/wiki#install-steps
Please ignore `/data` and instead use `/mnt/storage`. Please exercise caution with this, too. I think this instruction was from when I first started - so I haven't had a chance to verify if it still makes sense. And, of course, your particular contents/needs may require different permissions. My usage of `mergerfs` makes this a bit more confusing; but regardless it works.

The structure is based on [TRaSH Guides](https://trash-guides.info/Hardlinks/How-to-setup-for/Docker/), PerfectMediaServer, and [Servarr](https://wiki.servarr.com/docker-guide) docs.



>And follow-up question, do I need to run everything as root?

This should **not** be necessary. I run everything rootless. It's been a while since setup and I did a (poorer) job documenting this area... 
I would start by assigning a non-root user to the `docker` group ([wiki](https://github.com/jgwehr/homelab-docker/wiki#install-docker)). Directories and files can be owned by `user:docker` (instead of user:user or root:root). Refer to this also: [Rootless Docker](https://docs.docker.com/engine/security/rootless/#rootless-docker-in-docker).

If you have questions or find more places to improve the documentation, let me know! By end of week I'll be able to check what I actualy have running on the server and post a follow up for you.

**Comment by micklynch** [comment]
Thank you! I'll try to set it up this weekend and make a note of any inconsistencies. Are you open to accepting PRs? I can open one with changes that I feel are needed.

Another example, should all these env params also point to `/mnt/storage`?
https://github.com/jgwehr/homelab-docker/blob/bf4da8767e0639bf835583f24848a67e77faee3b/.env.template#L15-L19

**Comment by jgwehr** [comment]
Sorry I've been very late responding - a few personal things slowing me down.

Here are the perms for `/srv/docker` - which is where I bind all my docker configs. The blurred users/groups are my user. Any inconsistencies here are **unintentional**. I don't understand linux perms as well as I want to, but I believe the ideal state is to have all of these owned by `non-root-user:docker`
![image](https://github.com/jgwehr/homelab-docker/assets/13216529/4cde55a7-92fe-4dc2-b3a2-4d3b5948a920)

Similar explanation for the drives (note, `storage` is the mergerfs endpoint). Though, I'm more comfortable with these being owned by root:root.
![image](https://github.com/jgwehr/homelab-docker/assets/13216529/f4938962-efef-4ba0-8e03-92cda4d02bcb)

And again, within one of the drives. Poor hygiene on my part, but it works. 
![image](https://github.com/jgwehr/homelab-docker/assets/13216529/62145007-19d6-40f0-9357-5705663cee1c)

Within the combined, mergerfs directory, all the directories used by docker are user:x
![image](https://github.com/jgwehr/homelab-docker/assets/13216529/9e2c29ab-ef7f-47d0-8c2d-5ac5b2257b91)

There's a bit more info on this in a dusty issue here: https://github.com/jgwehr/homelab-docker/issues/21


I get mostly blanks when I run `docker inspect $(docker ps -q) --format '{{.Config.User}} {{.Name}}'` - but I **do not use sudo** when I execute `docker compose up -d`. All of these containers _should_ show 1000:1000 aka the default user. This user has been added to the `docker` group.

**Comment by micklynch** [comment]
Thank you @jgwehr ! Very helpful. I have set-up the services that I need and it's up and running already, I don't use mergerfs. I'll read through you're comment to see if it improves anything. I'll need to wait until I have some tinkering time too..."_if it ain't broke..._" yadayada.
